import React, {useEffect, useState} from 'react';
import Footer from '../components/Footer';
import '../style/BlogPage.css';
import Header from '../components/Header';
import SingleBlog from './SingleBlog';
import BlogCard from '../components/BlogCard';

const BlogPage = () => {
    const [currentBlog,setCurrentBlog] = useState(-1);

    const onReturn = () => {
        setCurrentBlog(-1);
    }

    const blogSelection = (value) => {
        setCurrentBlog(value);
    }

    return (
        <div className="_blogLibrary">
            <Header />
                <div className="_blogMainDiv">
                    {/*
                    <SingleBlog date="10/21/2024" imgSrc={lion} returnCallback={onReturn} value={1}>
                        {"Why 10 billion lions could default all the pokemon"}
                        {`
                        Now I know what you might be thinking, there’s no way 10 billion lions could defeat all the pokemon, even if they have an absolutely atrocious numbers advantage. Additionally, all the arguments for lions winning involve ignoring any logic that the pokemon advocate presents, and simply repeating over and over how 10 billion is such a large number. Well, I’m here to present “legitimate” facts and logic. \n

Firstly, we need to analyze just how powerful the pokemon actually are. The pokedex and other in-game articles claim some have powers of gods, but today we shall challenge just how legitimate these claims are. We will begin with a discussion on the mass of the pokemon. Firstly, a fan classic, Groudon. Groudon resembles a lizard that stands on its hind legs, at a staggering 16 ft tall in Primal form, and weighing 999.7 kg. Impressive? Hardly. An average adult giraffe can weigh more, with males weighing in at 1200 kg on average, and standing at 11 ft tall from the shoulder. Looking merely from a mass perspective, even if all 1025 pokemon were the size of Primal Groudon, 1000 giraffe sized creatures would not come close to withstanding a wave of 10 billion adult lions, each of which would weigh an average of 250 kg. \n

The second point we need to address are the powers of the pokemon. Obviously, without any powers we wouldn’t even need 1 million lions, much less 10 billion to sweep the competition. However, some pokemon have mystical powers, from controlling time and space to breathing fire. But how effective are these powers? We will take a look at the most egregious one first, the power of Arceus. Supposedly a god that created the world, if those powers were true infinite lions wouldn’t be enough. But myths are typically just that, myths. From the combat we have seen in the show, Arceus’s main move appears to be hurling rocks in a pseudo meteor-shower, and it has shown vulnerability to being hit by its own flying rock. Seeing this vulnerability, I believe that 1 million lions should be enough to default Arceus, by simply flooding over it. It cannot hurl meteors fast enough to eliminate them, and the force generated by the flood of lions is much greater than the small rocks that hurt it in the show. If we evenly split the lions among each pokemon, we would attack with 100 million each, which is greatly overkill even for the strongest pokemon.\n

Of course, most pokemon are not gods, and have simple abilities such as breathing fire, or tacking the opponent. How powerful are these strikes? Well, we have seen Team Rocket, a team of mortal humans tank various signature blows, and recover fairly quickly, which proves that the actual lethality of the moves are very low. Thus, the amount of lions needed for the average pokemon is fairly low, most likely under 50, and we can allocate more of the lions to the stronger pokemon. \n
At the end of it all, the average pokemon is simply not strong enough to hold its own against the 100 million lions that would face it, causing even some of the stronger pokemon such as Dialga or Arceus to bear the wrath of upwards of a billion lions, which would easily flood them to death. In my opinion, this battle should not be as close as many people are making it out to be, with an easy victory for the lions.
                        `
                        }
                        
                    </SingleBlog>
                    */}
                </div>
            <Footer href="/home#blog" />
        </div>
    );
}
export default BlogPage;